doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        driver: 'pdo_mysql'
        server_version: '8.0.1'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        logging: true 
        
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppLogin:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Login/Domain/Model'
                prefix: 'App\Auth\Login\Domain\Model'
                alias: AppLogin
            AppSoporte:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Soporte/Dominio/Entidades'
                prefix: 'App\Soporte\Dominio\Entidades'
                alias: AppSoporte
        controller_resolver:
            auto_mapping: true