security:
    providers:
        app_user_provider:
            id: App\Auth\Login\Infrastructure\Security\SymfonySecurityAdapter

    firewalls:
        main:
            form_login:
                login_path: /login
                check_path: /login
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Auth\Login\Infrastructure\Security\LoginFormAuthenticator
            entry_point: App\Auth\Login\Infrastructure\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/, roles: ROLE_USER }
