# config/routes.yaml

login:
    path: '/login'
    controller: 'App\Auth\Login\Infraestructura\Controlador\LoginController::login'

logout:
    path: '/logout'
    controller: 'App\Auth\Login\Infraestructura\Controlador\LoginController::logout'
