services:

    App\Auth\Login\Infrastructure\Security\SymfonyPasswordHasher:
        arguments:
            $passwordHasher: '@security.password_hasher'
    
    App\Auth\Login\Domain\Service\PasswordHasherInterface:
        alias: 'App\Auth\Login\Infrastructure\Security\SymfonyPasswordHasher'

    App\Auth\Login\Application\UserService:
        arguments:
            $userRepository: '@App\Auth\Login\Infrastructure\Persistence\UserRepository'
            $passwordHasher: '@App\Auth\Login\Domain\Service\PasswordHasherInterface'
            $rolRepository: '@App\Auth\Login\Infrastructure\Persistence\RolRepository'

    App\Auth\Login\Application\AuthenticationService:
        arguments: ['@App\Auth\Login\Domain\Repository\UserRepositoryInterface']

    App\Auth\Login\Domain\Repository\UserRepositoryInterface: 
        alias: App\Auth\Login\Infrastructure\Persistence\UserRepository

    App\Auth\Login\Infrastructure\Persistence\UserRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']
        
    App\Auth\Login\Infrastructure\Persistence\RolRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']

    App\Auth\Login\Infrastructure\Security\LoginFormAuthenticator:
        arguments:
            $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
    
    App\Auth\Login\Infrastructure\Security\SymfonySecurityAdapter:
        arguments:
            $userRepository: '@App\Auth\Login\Domain\Repository\UserRepositoryInterface'
    
#soporte
    App\Soporte\Aplicacion\Servicio\SoporteService:
        arguments:
            $soporteRepository: '@App\Soporte\Infraestructura\Persistencia\SoporteRepository'
    
    App\Soporte\Aplicacion\Servicio\UsuarioSoporteService:
        arguments:
            $usuarioSoporteRepository: '@App\Soporte\Infraestructura\Persistencia\UsuarioSoporteRepository'
            
    App\Soporte\Infraestructura\Persistencia\SoporteRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']

        
    App\Soporte\Infraestructura\Persistencia\UsuarioSoporteRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']

#usuario externo
    App\Soporte\Aplicacion\Servicio\UsuarioExternoService:
        arguments:
            $usuarioExternoRepository: '@App\Soporte\Infraestructura\Persistencia\UsuarioExternoRepository'

            
    App\Soporte\Infraestructura\Persistencia\UsuarioExternoRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']

    App\Soporte\Aplicacion\Controlador\SoporteController:
        autowire: true
        autoconfigure: true
        public: false

    App\Home\HomeController:
        autowire: true
        autoconfigure: true
        public: false


    App\Auth\Login\Application\Controller\LoginController:
        autowire: true
        autoconfigure: true
        public: false

    App\Auth\Login\Application\Controller\UserController:
        autowire: true
        autoconfigure: true
        public: false


    App\dashboard\Infraestructura\Controlador\DashboardController:
        autowire: true
        autoconfigure: true
        public: false

    doctrine.orm.metadata.annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader

    #seguridad
    App\Seguridad\DetectorInyecccionSQL:
