
services:
    # Servicio de autenticación
    App\Auth\Login\Aplicacion\Servicios\AutenticacionService:
        # Puedes definir cualquier configuración específica del servicio aquí
        # Por ejemplo, inyección de dependencias
        arguments:
            $userRepository: '@App\Auth\Login\Dominio\Repositorios\UsuarioRepositoryInterface'
        

    # Repositorio de usuario
    App\Auth\Login\Dominio\Repositorios\UsuarioRepositoryInterface:
        # Define el servicio como una interfaz
        class: App\Auth\Login\Infraestructura\Repositorios\UsuarioRepository

    App\Auth\Login\Infraestructura\Controlador\LoginController:
            # Puedes agregar cualquier configuración adicional aquí
            # Por ejemplo, la configuración de las dependencias
            autowire: true
            autoconfigure: true